name: Karate Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  karate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.5'

      - name: Run Karate tests
        run: npm run karate
